#
# 配置alias
#
alias l='ls -GA'
alias ls='ls -G'
alias lsc='LC_COLLATE=C ls -G'
alias la='ls -GA'
alias ll='ls -Gl'
alias tailf='tail -f'
alias grep='grep --color'
alias pi='ssh mz@192.168.1.110'

## ai相关
alias ai='aichat'
alias aiconf='cd "${HOME}/Library/Application Support/aichat"'
### 使用工具
alias aitool='aichat -r %functions%'
### 使用工具
alias ainews='aichat -r news'
### 中英翻译
alias aitran='aichat -r translate'
### 角色扮演
alias aiplay='aichat -r cosplay'

#
# 配置HomeBrew
#
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.aliyun.com/homebrew/homebrew-bottles"
export HOMEBREW_API_DOMAIN="https://mirrors.aliyun.com/homebrew/homebrew-bottles/api"
export HOMEBREW_PIP_INDEX_URL="http://mirrors.aliyun.com/pypi/simple"
export HOMEBREW_NO_AUTO_UPDATE=true # 避免自动更新耗
if [ -f /opt/homebrew/bin/brew ]; then
    eval $(/opt/homebrew/bin/brew shellenv)
fi

#
# 配置node
#
if [ -f "/opt/local/share/nvm/init-nvm.sh" ]; then
    source /opt/local/share/nvm/init-nvm.sh
fi

#
# 配置python
#
export PIP_INDEX_URL=$HOMEBREW_PIP_INDEX_URL
export UV_INDEX_URL=$HOMEBREW_PIP_INDEX_URL
export HF_ENDPOINT="https://hf-mirror.com"
if [ -f "$HOME/.local/bin/env" ]; then
    . "$HOME/.local/bin/env"
fi

#
# 其它配置
#
# export PS1="\[\e]2;\u@\h\a\]\[\e[01;36m\]\u\[\e[01;35m\]@\[\e[01;32m\]\H\[\e[00m\]:\[\e[01;34m\]\w$\[\e[00m\] "
# PS1="\[\e[32;40m\]\u:\[\e[36;40m\]\w\[\e[0m\] \$ "
export EDITOR=vim # for glow
export PATH="${HOME}/Dev/bin:${HOME}/Dev/unix_learn/bin:$PATH"

# 
# 欢迎语
#
# fortune | cowsay -f $(cowsay -l | tr ' ' '\n' | gshuf -n1) | lolcat
# fortune chinese tang300 song100 | lolcat
